// src/domains/rng/types/index.ts
// Domain-specific types and interfaces for rng
// Generated by 02-GenerateDomainStubs.ps1

export interface IRNGService {
  random(): number;
  randomInt(min: number, max: number, seed?: number): number;
  setSeed(seed: number): void;
  dispose(): void;
}
