// Generated from group_traits/trait_banks/force_calculation/attack_force_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { $1 } from '../../types/trait';

export const ATTACK_FORCE_CALCULATION_TRAITS = [
    {
      "name": "Aggressive Repulsion",
      "description": "Particles aggressively repel others",
      "rarityTier": "Common",
      "type": "Repulsion",
      "strengthMultiplier": 1.5,
      "rangeMultiplier": 1,
      "falloff": "linear",
      "physicsLogic": {
        "forceFunction": "linearRepulsion",
        "thresholdDistance": 3,
        "maxForce": 7
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ff3333"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Impact Force",
          "Kinetic Discharge"
        ]
      }
    },
    {
      "name": "Impact Force",
      "description": "Particles generate strong impact forces",
      "rarityTier": "Uncommon",
      "type": "Repulsion",
      "strengthMultiplier": 1.6,
      "rangeMultiplier": 1.1,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "impactForce",
        "thresholdDistance": 2.8,
        "maxForce": 7.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ff5555"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Kinetic Discharge",
          "Explosive Force"
        ]
      }
    },
    {
      "name": "Kinetic Discharge",
      "description": "Particles discharge kinetic energy",
      "rarityTier": "Rare",
      "type": "Repulsion",
      "strengthMultiplier": 1.7,
      "rangeMultiplier": 1.2,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "kineticDischarge",
        "thresholdDistance": 2.6,
        "maxForce": 8
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ff7777"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Explosive Force",
          "Shockwave Generation"
        ]
      }
    },
    {
      "name": "Explosive Force",
      "description": "Particles generate explosive repulsive forces",
      "rarityTier": "Rare",
      "type": "Repulsion",
      "strengthMultiplier": 1.8,
      "rangeMultiplier": 1.3,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "explosiveForce",
        "thresholdDistance": 2.4,
        "maxForce": 8.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ff9999"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Shockwave Generation",
          "Quantum Disruption"
        ]
      }
    },
    {
      "name": "Shockwave Generation",
      "description": "Particles generate powerful shockwaves",
      "rarityTier": "Epic",
      "type": "Repulsion",
      "strengthMultiplier": 1.9,
      "rangeMultiplier": 1.4,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "shockwaveGeneration",
        "thresholdDistance": 2.2,
        "maxForce": 9
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffaaaa"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Disruption",
          "Temporal Disruption"
        ]
      }
    },
    {
      "name": "Quantum Disruption",
      "description": "Particles disrupt quantum states",
      "rarityTier": "Epic",
      "type": "Repulsion",
      "strengthMultiplier": 2,
      "rangeMultiplier": 1.5,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "quantumDisruption",
        "thresholdDistance": 2,
        "maxForce": 9.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffbbbb"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Disruption",
          "Reality Fracture"
        ]
      }
    },
    {
      "name": "Temporal Disruption",
      "description": "Particles disrupt temporal coherence",
      "rarityTier": "Legendary",
      "type": "Repulsion",
      "strengthMultiplier": 2.1,
      "rangeMultiplier": 1.6,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "temporalDisruption",
        "thresholdDistance": 1.8,
        "maxForce": 10
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffcccc"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Fracture",
          "Cosmic Annihilation"
        ]
      }
    },
    {
      "name": "Reality Fracture",
      "description": "Particles fracture reality with repulsive force",
      "rarityTier": "Legendary",
      "type": "Repulsion",
      "strengthMultiplier": 2.2,
      "rangeMultiplier": 1.7,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "realityFracture",
        "thresholdDistance": 1.6,
        "maxForce": 10.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffdddd"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilation",
          "Void Eruption"
        ]
      }
    },
    {
      "name": "Cosmic Annihilation",
      "description": "Particles annihilate with cosmic-scale forces",
      "rarityTier": "Mythic",
      "type": "Repulsion",
      "strengthMultiplier": 2.3,
      "rangeMultiplier": 1.8,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "cosmicAnnihilation",
        "thresholdDistance": 1.4,
        "maxForce": 11
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffeeee"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Void Eruption"
        ]
      }
    },
    {
      "name": "Void Eruption",
      "description": "Particles erupt with void energy",
      "rarityTier": "Mythic",
      "type": "Repulsion",
      "strengthMultiplier": 2.4,
      "rangeMultiplier": 1.9,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "voidEruption",
        "thresholdDistance": 1.2,
        "maxForce": 11.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilation"
        ]
      }
    }
  ];

export default ATTACK_FORCE_CALCULATION_TRAITS;

