// Generated from group_traits/trait_banks/behavior/attack_behavior_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { $1 } from '../../types/trait';

export const ATTACK_BEHAVIOR_TRAITS = [
    {
      "name": "Aggressive Pursuit",
      "description": "Particles aggressively pursue targets",
      "rarityTier": "Common",
      "role": "ATTACK",
      "type": "Flocking",
      "physicsLogic": {
        "strength": 0.7,
        "range": 15,
        "priority": 0.8,
        "persistence": 0.7,
        "frequency": 0.5,
        "additionalParameters": {
          "pursuitSpeed": 0.8,
          "targetingAccuracy": 0.7
        }
      },
      "visualEffects": {
        "particleEffect": "aggressive_glow",
        "trailEffect": "pursuit_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Flanking Maneuver",
          "Piercing Strike"
        ]
      }
    },
    {
      "name": "Flanking Maneuver",
      "description": "Particles flank and surround targets",
      "rarityTier": "Uncommon",
      "role": "ATTACK",
      "type": "Flocking",
      "physicsLogic": {
        "strength": 0.75,
        "range": 18,
        "priority": 0.85,
        "persistence": 0.75,
        "frequency": 0.4,
        "additionalParameters": {
          "flankingAngle": 120,
          "surroundFactor": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "flanking_blur",
        "trailEffect": "tactical_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Piercing Strike",
          "Explosive Burst"
        ]
      }
    },
    {
      "name": "Piercing Strike",
      "description": "Particles form piercing strike formations",
      "rarityTier": "Rare",
      "role": "ATTACK",
      "type": "Flowing",
      "physicsLogic": {
        "strength": 0.8,
        "range": 20,
        "priority": 0.9,
        "persistence": 0.8,
        "frequency": 0.3,
        "additionalParameters": {
          "piercingPower": 0.9,
          "strikeVelocity": 1.2
        }
      },
      "visualEffects": {
        "particleEffect": "piercing_glow",
        "trailEffect": "strike_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Explosive Burst",
          "Vortex Strike"
        ]
      }
    },
    {
      "name": "Explosive Burst",
      "description": "Particles burst outward in explosive patterns",
      "rarityTier": "Rare",
      "role": "ATTACK",
      "type": "Pulsation",
      "physicsLogic": {
        "strength": 0.85,
        "range": 25,
        "priority": 0.95,
        "persistence": 0.7,
        "frequency": 0.6,
        "additionalParameters": {
          "explosiveForce": 1,
          "burstRadius": 15
        }
      },
      "visualEffects": {
        "particleEffect": "explosive_flash",
        "trailEffect": "shockwave_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Strike",
          "Quantum Assault"
        ]
      }
    },
    {
      "name": "Vortex Strike",
      "description": "Particles form a vortex that pulls and strikes",
      "rarityTier": "Epic",
      "role": "ATTACK",
      "type": "Rotation",
      "physicsLogic": {
        "strength": 0.9,
        "range": 30,
        "priority": 1,
        "persistence": 0.85,
        "frequency": 0.5,
        "additionalParameters": {
          "vortexPull": 0.8,
          "rotationalVelocity": 1
        }
      },
      "visualEffects": {
        "particleEffect": "vortex_spiral",
        "trailEffect": "spiral_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Assault",
          "Temporal Strike"
        ]
      }
    },
    {
      "name": "Quantum Assault",
      "description": "Particles attack through quantum tunneling",
      "rarityTier": "Epic",
      "role": "ATTACK",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 0.95,
        "range": 35,
        "priority": 1,
        "persistence": 0.9,
        "frequency": 0.4,
        "additionalParameters": {
          "quantumTunneling": 0.9,
          "phaseShiftProbability": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "quantum_shift",
        "trailEffect": "probability_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Strike",
          "Reality Shatter"
        ]
      }
    },
    {
      "name": "Temporal Strike",
      "description": "Particles strike through temporal distortions",
      "rarityTier": "Legendary",
      "role": "ATTACK",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1,
        "range": 40,
        "priority": 1,
        "persistence": 0.95,
        "frequency": 0.3,
        "additionalParameters": {
          "temporalDistortion": 0.9,
          "timeSlipFactor": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "time_fracture",
        "trailEffect": "temporal_echo",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Shatter",
          "Cosmic Annihilation"
        ]
      }
    },
    {
      "name": "Reality Shatter",
      "description": "Particles shatter the fabric of reality",
      "rarityTier": "Legendary",
      "role": "ATTACK",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.1,
        "range": 45,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.2,
        "additionalParameters": {
          "realityFracture": 0.9,
          "dimensionalRift": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "reality_crack",
        "trailEffect": "dimensional_tear",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilation",
          "Void Rend"
        ]
      }
    },
    {
      "name": "Cosmic Annihilation",
      "description": "Particles channel cosmic forces of destruction",
      "rarityTier": "Mythic",
      "role": "ATTACK",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.2,
        "range": 50,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.1,
        "additionalParameters": {
          "annihilationForce": 1,
          "cosmicDestructionRadius": 25
        }
      },
      "visualEffects": {
        "particleEffect": "cosmic_flare",
        "trailEffect": "destruction_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Void Rend"
        ]
      }
    },
    {
      "name": "Void Rend",
      "description": "Particles tear open the void between realities",
      "rarityTier": "Mythic",
      "role": "ATTACK",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.3,
        "range": 55,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.05,
        "additionalParameters": {
          "voidTearStrength": 1,
          "existentialErasure": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "void_tear",
        "trailEffect": "nothingness_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilation"
        ]
      }
    }
  ];

export default ATTACK_BEHAVIOR_TRAITS;

