// Generated from group_traits/trait_banks/visual/attack_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { $1 } from '../../types/trait';

export const ATTACK_VISUAL_TRAITS = [
    {
      "shape": "Arrow",
      "colorScheme": "Red Gradient",
      "visualEffect": "Sharp Edge",
      "rarityTier": "Common",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "ConeGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.9,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#ff3333"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0.2,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spear",
          "Glowing Arrow"
        ]
      }
    },
    {
      "shape": "Spear",
      "colorScheme": "Crimson",
      "visualEffect": "Piercing Glow",
      "rarityTier": "Uncommon",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomSpearGeometry",
        "material": "MeshStandardMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#ff5555"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0.3,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Blade",
          "Energy Spear"
        ]
      }
    },
    {
      "shape": "Blade",
      "colorScheme": "Scarlet",
      "visualEffect": "Cutting Edge",
      "rarityTier": "Rare",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomBladeGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.95,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#ff7777"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.4,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Shard",
          "Energy Blade"
        ]
      }
    },
    {
      "shape": "Shard",
      "colorScheme": "Ruby",
      "visualEffect": "Fragmentation",
      "rarityTier": "Rare",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomShardGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.85,
        "emissive": true,
        "opacity": 0.95,
        "colorHex": "#ff9999"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0.5,
        "trailLength": 1.2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Nova",
          "Crystal Shard"
        ]
      }
    },
    {
      "shape": "Nova",
      "colorScheme": "Fiery Red",
      "visualEffect": "Explosive Burst",
      "rarityTier": "Epic",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomNovaGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.1,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#ffaaaa"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0.6,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Blade",
          "Quantum Spike"
        ]
      }
    },
    {
      "shape": "Vortex Blade",
      "colorScheme": "Inferno",
      "visualEffect": "Spinning Edge",
      "rarityTier": "Epic",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomVortexBladeGeometry",
        "material": "ShaderMaterial",
        "scale": 1.05,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#ffbbbb"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.8,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Spike",
          "Phantom Blade"
        ]
      }
    },
    {
      "shape": "Quantum Spike",
      "colorScheme": "Quantum Red",
      "visualEffect": "Phase Shift",
      "rarityTier": "Legendary",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomQuantumSpikeGeometry",
        "material": "ShaderMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#ffcccc"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.7,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Phantom Blade",
          "Reality Shredder"
        ]
      }
    },
    {
      "shape": "Phantom Blade",
      "colorScheme": "Ethereal Red",
      "visualEffect": "Phasing Edge",
      "rarityTier": "Legendary",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomPhantomGeometry",
        "material": "ShaderMaterial",
        "scale": 1.15,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ffdddd"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.9,
        "trailLength": 3.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Shredder",
          "Void Rend"
        ]
      }
    },
    {
      "shape": "Reality Shredder",
      "colorScheme": "Dimensional Red",
      "visualEffect": "Reality Tear",
      "rarityTier": "Mythic",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomShredderGeometry",
        "material": "ShaderMaterial",
        "scale": 1.2,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ffeeee"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 1,
        "trailLength": 4
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Void Rend",
          "Cosmic Annihilator"
        ]
      }
    },
    {
      "shape": "Void Rend",
      "colorScheme": "Cosmic Red",
      "visualEffect": "Existential Tear",
      "rarityTier": "Mythic",
      "role": "ATTACK",
      "renderingProperties": {
        "geometry": "CustomVoidGeometry",
        "material": "ShaderMaterial",
        "scale": 1.25,
        "emissive": true,
        "opacity": 0.6,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 0.9,
        "rotationSpeed": 1.1,
        "trailLength": 4.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilator",
          "Reality Shredder"
        ]
      }
    }
  ];

export default ATTACK_VISUAL_TRAITS;

