// Generated from group_traits/trait_banks/visual/movement_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { $1 } from '../../types/trait';

export const MOVEMENT_VISUAL_TRAITS = [
    {
      "shape": "Streamlined",
      "colorScheme": "Blue Gradient",
      "visualEffect": "Speed Trail",
      "rarityTier": "Common",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomStreamlinedGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.8,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#3399ff"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Wave Form",
          "Aerodynamic"
        ]
      }
    },
    {
      "shape": "Wave Form",
      "colorScheme": "Azure",
      "visualEffect": "Oscillating Trail",
      "rarityTier": "Uncommon",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomWaveGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.75,
        "emissive": true,
        "opacity": 0.95,
        "colorHex": "#55aaff"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Aerodynamic",
          "Slipstream"
        ]
      }
    },
    {
      "shape": "Aerodynamic",
      "colorScheme": "Cerulean",
      "visualEffect": "Air Current",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomAerodynamicGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.7,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#77bbff"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.1,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstream",
          "Vortex"
        ]
      }
    },
    {
      "shape": "Slipstream",
      "colorScheme": "Sky Blue",
      "visualEffect": "Flow Channel",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomSlipstreamGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.65,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#99ccff"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0.2,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex",
          "Quantum Leap"
        ]
      }
    },
    {
      "shape": "Vortex",
      "colorScheme": "Cobalt",
      "visualEffect": "Spiral Flow",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomVortexGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.6,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#aaddff"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.5,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Leap",
          "Hypersonic"
        ]
      }
    },
    {
      "shape": "Hypersonic",
      "colorScheme": "Electric Blue",
      "visualEffect": "Shock Wave",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomHypersonicGeometry",
        "material": "ShaderMaterial",
        "scale": 0.55,
        "emissive": true,
        "opacity": 0.75,
        "colorHex": "#bbeeff"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.3,
        "trailLength": 3.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Leap",
          "Temporal Slip"
        ]
      }
    },
    {
      "shape": "Quantum Leap",
      "colorScheme": "Quantum Blue",
      "visualEffect": "Probability Trail",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomQuantumGeometry",
        "material": "ShaderMaterial",
        "scale": 0.5,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ccffff"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0,
        "trailLength": 4
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Slip",
          "Dimensional Shift"
        ]
      }
    },
    {
      "shape": "Temporal Slip",
      "colorScheme": "Chrono Blue",
      "visualEffect": "Time Echo",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomTemporalGeometry",
        "material": "ShaderMaterial",
        "scale": 0.45,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ddffff"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.1,
        "trailLength": 4.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Shift",
          "Cosmic Velocity"
        ]
      }
    },
    {
      "shape": "Dimensional Shift",
      "colorScheme": "Ethereal Blue",
      "visualEffect": "Reality Blur",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomDimensionalGeometry",
        "material": "ShaderMaterial",
        "scale": 0.4,
        "emissive": true,
        "opacity": 0.6,
        "colorHex": "#eeffff"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.2,
        "trailLength": 5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Reality Surfer"
        ]
      }
    },
    {
      "shape": "Reality Surfer",
      "colorScheme": "Cosmic Blue",
      "visualEffect": "Multiverse Wake",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "renderingProperties": {
        "geometry": "CustomRealitySurferGeometry",
        "material": "ShaderMaterial",
        "scale": 0.35,
        "emissive": true,
        "opacity": 0.55,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 0.3,
        "trailLength": 5.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Dimensional Shift"
        ]
      }
    }
  ];

export default MOVEMENT_VISUAL_TRAITS;

