// src/domains/group/types/index.ts
// Domain-specific types and interfaces for group
// Generated by 02-GenerateDomainStubs.ps1

export interface ParticleGroup {
  id: string;
  members: string[];
  metadata?: Record<string, any>;
}

export interface IGroupService {
  formGroup(particleIds: string[]): ParticleGroup;
  getGroup(id: string): ParticleGroup | undefined;
  dissolveGroup(id: string): void;
  dispose(): void;
}
