// src/domains/particle/index.ts
// Domain export index for particle
// Generated by 02-GenerateDoainStubs.ps1

// Service exports
export { particleService } from './services/ParticleService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IParticleService } from './interfaces/IParticleService';
