// src/domains/rng/index.ts
// Domain export index for rng
// Generated by 02-GenerateDomainStubs.ps1

// Service exports
export { rngService } from './services/RNGService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IRNGService } from './types';
