// src/domains/rendering/index.ts
// Domain export index for rendering
// Generated by 02-GenerateDomainStubs.ps1

// Service exports
export { renderingService } from './services/RenderingService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IRenderingService } from './types';
