// src/domains/bitcoin/index.ts
// Domain export index for bitcoin
// Generated by 02-GenerateDoainStubs.ps1

// Service exports
export { bitcoinService } from './services/BitcoinService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IBitcoinService } from './types';
