// src/domains/effect/index.ts
// Domain export index for effect
// Generated by 02-GenerateDomainStubs.ps1

// Service exports
export { effectService } from './services/EffectService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IEffectService } from './types';
