// src/domains/rendering/types/index.ts
// Domain-specific types and interfaces for rendering
// Generated by 02-GenerateDomainStubs.ps1

import { Object3D } from 'three';

export interface IRenderingService {
  initialize(canvas: HTMLCanvasElement): void;
  renderFrame(delta: number): void;
  addObject(obj: Object3D): void;
  removeObject(obj: Object3D): void;
  dispose(): void;
}
