// src/domains/formation/index.ts
// Domain export index for formation
// Generated by 02-GenerateDoainStubs.ps1

// Service exports
export { formationService } from './services/FormationService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IFormationService } from './types';
