// src/domains/particle/types/index.ts
// Domain-specific types and interfaces for particle
// Generated by 02-GenerateDomainStubs.ps1

import { IParticleCore, IParticleTraits } from '@/shared/types/core.types';
import { IBaseService } from '@/shared/interfaces/base.interfaces';

export interface Particle extends IParticleCore {
  readonly traits: IParticleTraits;
}

export interface IParticleService extends IBaseService {
  createParticle(initialTraits?: Partial<IParticleTraits>): Particle;
  getParticleById(id: string): Particle | undefined;
  updateParticles(delta: number): void;
  getAllParticles(): Particle[];
  getParticleCount(): number;
}
