// src/domains/particle/types/index.ts
// Domain-specific types and interfaces for particle
// Generated by 02-GenerateDomainStubs.ps1

import { Vector3 } from 'three';

export interface Particle {
  id: string;
  position: Vector3;
  velocity: Vector3;
  age: number;
  lifetime: number;
  active: boolean;
}

export interface IParticleService {
  createParticle(position?: Vector3, velocity?: Vector3): Particle;
  getParticleById(id: string): Particle | undefined;
  updateParticles(deltaTime: number): void;
  getAllParticles(): Particle[];
  getParticleCount(): number;
  dispose(): void;
}
