// src/domains/group/index.ts
// Domain export index for group
// Generated by 02-GenerateDomainStubs.ps1

// Service exports
export { groupService } from './services/GroupService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IGroupService } from './types';
