// src/domains/bitcoin/types/index.ts
// Domain-specific types and interfaces for bitcoin
// Generated by 02-GenerateDomainStubs.ps1

export interface BitcoinBlockInfo {
  height: number;
  hash: string;
  timestamp: number;
  nonce: number;
}

export interface IBitcoinService {
  fetchBlockInfo(blockNumber: number): Promise<BitcoinBlockInfo>;
  getCachedBlockInfo(blockNumber: number): BitcoinBlockInfo | undefined;
  fetchInscriptionContent(inscriptionId: string): Promise<string>;
  dispose(): void;
}
