// src/domains/formation/types/index.ts
// Domain-specific types and interfaces for formation
// Generated by 02-GenerateDomainStubs.ps1

import { IFormationCore, IFormationMetadata, IVector3 } from '@/shared/types/core.types';
import { ICacheableService, ICacheStats } from '@/shared/interfaces/base.interfaces';

export interface FormationPattern extends IFormationCore {
  readonly metadata: IFormationMetadata;
}

export interface IFormationService extends ICacheableService {
  getFormationPattern(patternId: string): FormationPattern | undefined;
  applyFormation(patternId: string, particleIds: string[]): void;
  registerPattern(pattern: FormationPattern): void;
  blendFormations(patterns: FormationPattern[], weights: number[]): FormationPattern;
  getCachedBlend(key: string): FormationPattern | undefined;
  setCacheLimit(maxSize: number): void;
}
