// src/domains/formation/types/index.ts
// Domain-specific types and interfaces for formation
// Generated by 02-GenerateDomainStubs.ps1

import { Vector3 } from 'three';

export interface FormationPattern {
  id: string;
  name: string;
  positions: Vector3[];
  scale: number;
  rotation: number;
}

export interface IFormationService {
  getFormationPattern(patternId: string): FormationPattern | undefined;
  applyFormation(patternId: string, particleIds: string[]): void;
  registerPattern(pattern: FormationPattern): void;
  blendFormations(patterns: FormationPattern[], weights: number[]): FormationPattern;
  getCachedBlend(key: string): FormationPattern | undefined;
  setCacheLimit(maxSize: number): void;
  dispose(): void;
}
