// src/domains/animation/index.ts
// Domain export index for animation
// Generated by 02-GenerateDoainStubs.ps1

// Service exports
export { animationService } from './services/AnimationService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IAnimationService } from './interfaces/IAnimationService';
