// src/domains/physics/index.ts
// Domain export index for physics
// Generated by 02-GenerateDoainStubs.ps1

// Service exports
export { physicsService } from './services/PhysicsService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { IPhysicsService } from './types';
