/**
 * @fileoverview Physics Domain Exports
 * @description Main export file for Physics domain (generated by script)
 * @version 1.0.0
 */

// Service exports
export { PhysicsService, physicsService } from "./services/PhysicsService"

// Interface exports
export type {
  IPhysicsService,
  PhysicsConfig,
  ParticlePhysics,
  Transform,
  PhysicsMetrics
} from "./interfaces/IPhysicsService"

// Type exports
export type {
  PhysicsAlgorithm,
  CollisionMethod,
  DistributionPattern,
  InterpolationType,
  GeometryBounds,
  PhysicsState
} from "./types/physics.types"
