// src/domains/effect/types/index.ts
// Domain-specific types and interfaces for effect
// Generated by 02-GenerateDomainStubs.ps1

export interface EffectConfig {
  duration: number;
  intensity: number;
  parameters?: Record<string, any>;
}

export interface IEffectService {
  triggerEffect(name: string, options?: any): void;
  registerEffectPreset(name: string, config: EffectConfig): void;
  dispose(): void;
}
