// src/domains/trait/index.ts
// Domain export index for trait
// Generated by 02-GenerateDomainStubs.ps1

// Service exports
export { traitService } from './services/TraitService';

// Type exports
export * from './types';

// Interface re-exports for easier imports
export type { ITraitService } from './types';
