// src/domains/trait/types/index.ts
// Domain-specific types and interfaces for trait
// Generated by 02-GenerateDomainStubs.ps1

import { OrganismTraits } from '@/domains/trait/types/trait.types';

export interface ITraitService {
  generateTraitsForOrganism(id: string, blockNonce?: number): OrganismTraits;
  mutateTrait(traitType: string, currentValue: any): any;
  applyTraitsToOrganism(organismId: string, traits: OrganismTraits): void;
  dispose(): void;
}
