// src/domains/index.ts
// Master export for all domain services
// Auto-generated by 02-GenerateDomainStubs.ps1
export { renderingService } from './rendering/services/RenderingService';export { animationService } from './animation/services/AnimationService';export { effectService } from './effect/services/EffectService';export { traitService } from './trait/services/TraitService';export { physicsService } from './physics/services/PhysicsService';export { particleService } from './particle/services/ParticleService';export { formationService } from './formation/services/FormationService';export { groupService } from './group/services/GroupService';export { rngService } from './rng/services/RNGService';export { bitcoinService } from './bitcoin/services/BitcoinService';
