// src/domains/animation/types/index.ts
// Domain-specific types and interfaces for animation
// Generated by 02-GenerateDomainStubs.ps1

import { AnimationConfig } from '@/shared/types';

export interface IAnimationService {
  startAnimation(role: string, config: AnimationConfig): void;
  updateAnimations(delta: number): void;
  stopAnimation(role: string): void;
  stopAll(): void;
  dispose(): void;
}
