// src/domains/animation/types/index.ts
// Domain-specific types and interfaces for animation
// Generated by 02-GenerateDomainStubs.ps1

export interface AnimationConfig {
  duration: number;
  type: string;
  easing?: string;
  loop?: boolean;
}

export interface AnimationState {
  role: string;
  progress: number;
  duration: number;
  type: string;
}

export interface IAnimationService {
  startAnimation(role: string, config: AnimationConfig): void;
  updateAnimations(delta: number): void;
  stopAnimation(role: string): void;
  stopAll(): void;
  dispose(): void;
}
