// src/domains/physics/types/index.ts
// Domain-specific types and interfaces for physics
// Generated by 02-GenerateDomainStubs.ps1

import { IVector3 } from '@/shared/types';

export interface IPhysicsService {
  calculateDistribution(count: number, radius: number): IVector3[];
  applyGravity(position: IVector3, delta: number): IVector3;
  detectCollisions(particles: IVector3[]): boolean;
  dispose(): void;
}
