// src/domains/physics/types/index.ts
// Domain-specific types and interfaces for physics
// Generated by 02-GenerateDomainStubs.ps1

import { Vector3 } from '@/shared/types';

export interface IPhysicsService {
  calculateDistribution(count: number, radius: number): Vector3[];
  applyGravity(position: Vector3, delta: number): Vector3;
  detectCollisions(particles: Vector3[]): boolean;
  dispose(): void;
}
