name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Unit Tests
        run: npm run test:coverage
      - name: Validate Scripts
        run: pwsh ./scripts/VerifyCompliance.ps1
      - name: Bundle Size
        run: npm run build:analyze
      - uses: actions/upload-artifact@v3
        with:
          name: bundle-stats
          path: stats.json
  bundle-analysis:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Run bundle analyzer
        run: npm exec ts-node ./src/shared/services/bundleAnalyzerService.ts
      - uses: actions/upload-artifact@v3
        with:
          name: bundle-report
          path: dist/report.html
  perf-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with: { node-version: '18', cache: 'npm' }
      - run: npm ci
      - run: npm exec vitest run tests/performance --reporter verbose
