name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm eslint . --max-warnings=0
      - name: Type Check
        run: pnpm tsc --noEmit
      - name: Unit Tests
        run: pnpm vitest run --coverage
      - name: Validate Scripts
        run: pwsh ./scripts/VerifyCompliance.ps1
      - name: Bundle Size
        run: pnpm webpack --profile --json > stats.json
      - uses: actions/upload-artifact@v3
        with:
          name: bundle-stats
          path: stats.json
  bundle-analysis:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run bundle analyzer
        run: pnpm ts-node ./src/shared/services/bundleAnalyzerService.ts
      - uses: actions/upload-artifact@v3
        with:
          name: bundle-report
          path: dist/report.html
  perf-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile
      - run: pnpm vitest run tests/performance --reporter verbose
  e2e-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: pnpm playwright test
