name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Docker Build
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker Login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker Push
        run: docker push ghcr.io/${{ github.repository }}:latest
