name: Docs
on:
  push:
    branches: [main]
    paths: [ 'src/**', 'typedoc.json' ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Generate docs
        run: pnpm ts-node scripts/generateDocs.ts
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ">${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./docs/api
